/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import EDD.*;
import EDD.Hotel.*;
import HotelBooking.Manager;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author santi
 */
public class TEST extends javax.swing.JFrame {

    /**
     * Creates new form TEST
     */
    Manager manager = new Manager();
    boolean editado =false;
    int xMouse, yMouse;
    public TEST() {
        initComponents();
        Default.setVisible(true);
        
        Reservas.setVisible(false);
        CheckIn.setVisible(false);
        CheckOut.setVisible(false);
        Huesped.setVisible(false);
        History.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.JPanel();
        ReservasBut = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CheckInBut = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CheckOutBut = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HistoryBut = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HuespedesBut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Paneles = new javax.swing.JPanel();
        Default = new javax.swing.JPanel();
        Nombres = new javax.swing.JLabel();
        Reservas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ReservaText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BuscarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarReseva = new javax.swing.JTextArea();
        CheckIn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BuscarCheckIn = new javax.swing.JButton();
        CheckInText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CheckInMostrar = new javax.swing.JTextArea();
        CheckOut = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CheckOutText = new javax.swing.JTextField();
        BuscarCheckOut = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        MostrarCheckOut = new javax.swing.JTextArea();
        History = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        HistorialText = new javax.swing.JTextField();
        BuscarCheckOut1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MostrarHistorial = new javax.swing.JTextArea();
        Huesped = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ClienteText = new javax.swing.JTextField();
        BuscarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        MostrarCliente = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JPanel();
        XExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Botones.setBackground(new java.awt.Color(204, 204, 204));
        Botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReservasBut.setBackground(new java.awt.Color(150, 150, 150));
        ReservasBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReservasBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservasButMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/reservation.png"))); // NOI18N
        jLabel5.setText("Reservas");

        javax.swing.GroupLayout ReservasButLayout = new javax.swing.GroupLayout(ReservasBut);
        ReservasBut.setLayout(ReservasButLayout);
        ReservasButLayout.setHorizontalGroup(
            ReservasButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasButLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        ReservasButLayout.setVerticalGroup(
            ReservasButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Botones.add(ReservasBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, -1));

        CheckInBut.setBackground(new java.awt.Color(150, 150, 150));
        CheckInBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckInBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckInButMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/checkin.png"))); // NOI18N
        jLabel4.setText("Check In");

        javax.swing.GroupLayout CheckInButLayout = new javax.swing.GroupLayout(CheckInBut);
        CheckInBut.setLayout(CheckInButLayout);
        CheckInButLayout.setHorizontalGroup(
            CheckInButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckInButLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        CheckInButLayout.setVerticalGroup(
            CheckInButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Botones.add(CheckInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, -1));

        CheckOutBut.setBackground(new java.awt.Color(150, 150, 150));
        CheckOutBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckOutBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckOutButMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/checkout.png"))); // NOI18N
        jLabel2.setText("Check Out");

        javax.swing.GroupLayout CheckOutButLayout = new javax.swing.GroupLayout(CheckOutBut);
        CheckOutBut.setLayout(CheckOutButLayout);
        CheckOutButLayout.setHorizontalGroup(
            CheckOutButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckOutButLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        CheckOutButLayout.setVerticalGroup(
            CheckOutButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Botones.add(CheckOutBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, -1));

        HistoryBut.setBackground(new java.awt.Color(150, 150, 150));
        HistoryBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistoryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryButMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/historial.png"))); // NOI18N
        jLabel3.setText("Historial");

        javax.swing.GroupLayout HistoryButLayout = new javax.swing.GroupLayout(HistoryBut);
        HistoryBut.setLayout(HistoryButLayout);
        HistoryButLayout.setHorizontalGroup(
            HistoryButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryButLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        HistoryButLayout.setVerticalGroup(
            HistoryButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Botones.add(HistoryBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, -1));

        HuespedesBut.setBackground(new java.awt.Color(153, 153, 153));
        HuespedesBut.setForeground(new java.awt.Color(153, 153, 153));
        HuespedesBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HuespedesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HuespedesButMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/registro.png"))); // NOI18N
        jLabel1.setText("Huespedes");

        javax.swing.GroupLayout HuespedesButLayout = new javax.swing.GroupLayout(HuespedesBut);
        HuespedesBut.setLayout(HuespedesButLayout);
        HuespedesButLayout.setHorizontalGroup(
            HuespedesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HuespedesButLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );
        HuespedesButLayout.setVerticalGroup(
            HuespedesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Botones.add(HuespedesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HOTEL");
        Botones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 70));

        getContentPane().add(Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 390));

        Paneles.setBackground(new java.awt.Color(100, 100, 100));

        Default.setBackground(new java.awt.Color(100, 100, 100));
        Default.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombres.setBackground(new java.awt.Color(255, 255, 255));
        Nombres.setForeground(new java.awt.Color(204, 204, 204));
        Nombres.setText("Santiago Alvarez, Jonathan Sarli, Giampiero Bastidas");
        Default.add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        Reservas.setBackground(new java.awt.Color(100, 100, 100));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Reservaciones");

        ReservaText.setText("12.345.678");
        ReservaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservaTextMousePressed(evt);
            }
        });
        ReservaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaTextActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrese el numero de cedula del cliente");

        BuscarReserva.setBackground(new java.awt.Color(51, 51, 51));
        BuscarReserva.setForeground(new java.awt.Color(255, 255, 255));
        BuscarReserva.setText("Buscar Cliente");
        BuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarReservaActionPerformed(evt);
            }
        });

        MostrarReseva.setColumns(20);
        MostrarReseva.setRows(5);
        jScrollPane1.setViewportView(MostrarReseva);

        javax.swing.GroupLayout ReservasLayout = new javax.swing.GroupLayout(Reservas);
        Reservas.setLayout(ReservasLayout);
        ReservasLayout.setHorizontalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReservaText))
                        .addGap(18, 18, 18)
                        .addComponent(BuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        ReservasLayout.setVerticalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarReserva))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        CheckIn.setBackground(new java.awt.Color(100, 100, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Check In");

        BuscarCheckIn.setBackground(new java.awt.Color(51, 51, 51));
        BuscarCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        BuscarCheckIn.setText("Check In");
        BuscarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCheckInActionPerformed(evt);
            }
        });

        CheckInText.setText("12.345.678");
        CheckInText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckInTextMousePressed(evt);
            }
        });
        CheckInText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInTextActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingrese el Numero de Cedula");

        CheckInMostrar.setColumns(20);
        CheckInMostrar.setRows(5);
        jScrollPane5.setViewportView(CheckInMostrar);

        javax.swing.GroupLayout CheckInLayout = new javax.swing.GroupLayout(CheckIn);
        CheckIn.setLayout(CheckInLayout);
        CheckInLayout.setHorizontalGroup(
            CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addGroup(CheckInLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(CheckInLayout.createSequentialGroup()
                        .addGroup(CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckInText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BuscarCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckInLayout.setVerticalGroup(
            CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCheckIn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        CheckOut.setBackground(new java.awt.Color(100, 100, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Check Out");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingrese el Nombre y Apellido del cliente");

        CheckOutText.setText("Nombre Apellido");
        CheckOutText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckOutTextMousePressed(evt);
            }
        });
        CheckOutText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutTextActionPerformed(evt);
            }
        });

        BuscarCheckOut.setBackground(new java.awt.Color(51, 51, 51));
        BuscarCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        BuscarCheckOut.setText("Check Out");
        BuscarCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCheckOutActionPerformed(evt);
            }
        });

        MostrarCheckOut.setColumns(20);
        MostrarCheckOut.setRows(5);
        jScrollPane4.setViewportView(MostrarCheckOut);

        javax.swing.GroupLayout CheckOutLayout = new javax.swing.GroupLayout(CheckOut);
        CheckOut.setLayout(CheckOutLayout);
        CheckOutLayout.setHorizontalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
            .addGroup(CheckOutLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(CheckOutLayout.createSequentialGroup()
                        .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckOutText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BuscarCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckOutLayout.setVerticalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCheckOut))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        History.setBackground(new java.awt.Color(100, 100, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Historial de Habitaciones");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingrese el numeo de habitacion");

        HistorialText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialTextActionPerformed(evt);
            }
        });

        BuscarCheckOut1.setBackground(new java.awt.Color(51, 51, 51));
        BuscarCheckOut1.setForeground(new java.awt.Color(255, 255, 255));
        BuscarCheckOut1.setText("Ver Historial");
        BuscarCheckOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCheckOut1ActionPerformed(evt);
            }
        });

        MostrarHistorial.setColumns(20);
        MostrarHistorial.setRows(5);
        jScrollPane2.setViewportView(MostrarHistorial);

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(HistoryLayout.createSequentialGroup()
                        .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HistorialText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BuscarCheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistorialText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCheckOut1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Huesped.setBackground(new java.awt.Color(100, 100, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clientes actualmente hospedados");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ingrese el Nombre y Apellido del cliente");

        ClienteText.setText("Nombre Apellido");
        ClienteText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClienteTextMousePressed(evt);
            }
        });
        ClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTextActionPerformed(evt);
            }
        });

        BuscarCliente.setBackground(new java.awt.Color(51, 51, 51));
        BuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });

        MostrarCliente.setColumns(20);
        MostrarCliente.setRows(5);
        jScrollPane3.setViewportView(MostrarCliente);

        javax.swing.GroupLayout HuespedLayout = new javax.swing.GroupLayout(Huesped);
        Huesped.setLayout(HuespedLayout);
        HuespedLayout.setHorizontalGroup(
            HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HuespedLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(HuespedLayout.createSequentialGroup()
                            .addComponent(ClienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );
        HuespedLayout.setVerticalGroup(
            HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HuespedLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelesLayout = new javax.swing.GroupLayout(Paneles);
        Paneles.setLayout(PanelesLayout);
        PanelesLayout.setHorizontalGroup(
            PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(PanelesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(232, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Default, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );
        PanelesLayout.setVerticalGroup(
            PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelesLayout.createSequentialGroup()
                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(393, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(390, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(390, Short.MAX_VALUE)))
            .addGroup(PanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Default, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );

        getContentPane().add(Paneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 490, 390));

        jPanel1.setBackground(new java.awt.Color(241, 243, 249));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn.setBackground(new java.awt.Color(241, 243, 249));
        ExitBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });

        XExit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        XExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XExit.setText("X");

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitBtnLayout.createSequentialGroup()
                .addComponent(XExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(XExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservasButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservasButMouseClicked
        // TODO add your handling code here:
        ReservasBut.setBackground(new Color(100,100,100));
        Reservas.setVisible(true);
        
        CheckInBut.setBackground(new Color(150,150,150));
        CheckOutBut.setBackground(new Color(150,150,150));
        HistoryBut.setBackground(new Color(150,150,150));
        HuespedesBut.setBackground(new Color(150,150,150));
        CheckIn.setVisible(false);
        CheckOut.setVisible(false);
        Huesped.setVisible(false);
        History.setVisible(false);
        Default.setVisible(false);
    }//GEN-LAST:event_ReservasButMouseClicked

    private void CheckInButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckInButMouseClicked
        // TODO add your handling code here:
        CheckInBut.setBackground(new Color(100,100,100));
        CheckIn.setVisible(true);
        
        ReservasBut.setBackground(new Color(150,150,150));
        Reservas.setVisible(false);
        CheckOutBut.setBackground(new Color(150,150,150));
        CheckOut.setVisible(false);
        HistoryBut.setBackground(new Color(150,150,150));
        History.setVisible(false);
        HuespedesBut.setBackground(new Color(150,150,150));
        Huesped.setVisible(false);
        
        Default.setVisible(false);
    }//GEN-LAST:event_CheckInButMouseClicked

    private void CheckOutButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutButMouseClicked
        // TODO add your handling code here:
        CheckOutBut.setBackground(new Color(100,100,100));
        CheckOut.setVisible(true);
        
        ReservasBut.setBackground(new Color(150,150,150));
        Reservas.setVisible(false);
        CheckInBut.setBackground(new Color(150,150,150));
        CheckIn.setVisible(false);
        HistoryBut.setBackground(new Color(150,150,150));
        History.setVisible(false);
        HuespedesBut.setBackground(new Color(150,150,150));
        Huesped.setVisible(false);
        
        Default.setVisible(false);
        
    }//GEN-LAST:event_CheckOutButMouseClicked

    private void HistoryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryButMouseClicked
        // TODO add your handling code here:
        HistoryBut.setBackground(new Color(100,100,100));
        History.setVisible(true);
        
        ReservasBut.setBackground(new Color(150,150,150));
        Reservas.setVisible(false);
        CheckInBut.setBackground(new Color(150,150,150));
        CheckIn.setVisible(false);
        CheckOutBut.setBackground(new Color(150,150,150));
        CheckOut.setVisible(false);
        HuespedesBut.setBackground(new Color(150,150,150));
        Huesped.setVisible(false);
        
        Default.setVisible(false);
    }//GEN-LAST:event_HistoryButMouseClicked

    private void HuespedesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuespedesButMouseClicked
        // TODO add your handling code here:
        HuespedesBut.setBackground(new Color(100,100,100));
        Huesped.setVisible(true);
        
        ReservasBut.setBackground(new Color(150,150,150));
        Reservas.setVisible(false);
        CheckInBut.setBackground(new Color(150,150,150));
        CheckIn.setVisible(false);
        HistoryBut.setBackground(new Color(150,150,150));
        History.setVisible(false);
        CheckOutBut.setBackground(new Color(150,150,150));
        CheckOut.setVisible(false);
        
        Default.setVisible(false);
    }//GEN-LAST:event_HuespedesButMouseClicked

    private void ReservaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservaTextActionPerformed

    private void CheckInTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckInTextActionPerformed

    private void CheckOutTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckOutTextActionPerformed

    private void HistorialTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialTextActionPerformed

    private void ClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTextActionPerformed

    private void BuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarReservaActionPerformed
        // TODO add your handling code here:
        String inputCI = ReservaText.getText();
        try{
            int ci = Integer.parseInt(inputCI.replace(".","").replace(" ",""));
            Reserva reserva = (Reserva) manager.getReservas().search(ci, manager.getReservas().getRoot());
            if (reserva!=null) {
                MostrarReseva.setText(reserva.toPrint());
            }else{
                MostrarReseva.setText("No se ha encontrado una reserva afiliada \ncon un cliente de cedula: "+ci);
            }
            
        }catch(Exception e){
            MostrarReseva.setText("No se ha encontrado una reserva afiliada \ncon un cliente de cedula: "+inputCI);
        }
        
        
    }//GEN-LAST:event_BuscarReservaActionPerformed

    private void BuscarCheckOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCheckOut1ActionPerformed
        // TODO add your handling code here:
        String numHab = HistorialText.getText();
        try{
            int num = Integer.parseInt(numHab.replace(" ",""));
            Habitacion hab = (Habitacion) manager.getHab_historico().search(num, manager.getHab_historico().getRoot());
            if (hab!=null) {
                String texto = hab.printHistory();
                if (texto.isBlank()) {   
                    MostrarHistorial.setText("La habitacion "+num+" nunca ha tenido huespedes!");
                }else{
                    MostrarHistorial.setText("La lista de huespedes de la habitacion "+num+" es:\n"+texto);
                }

            }else{
                MostrarHistorial.setText("Debe ingresar un numero de habitacion valido.\nEl hotel tiene habitaciones del 1 al 300");
            } 
        }catch(Exception e){
            MostrarHistorial.setText("Debe ingresar un numero de habitacion valido.\nEl hotel tiene habitaciones del 1 al 300");
        }
    }//GEN-LAST:event_BuscarCheckOut1ActionPerformed

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
        String clientenombre = ClienteText.getText();
        try{
        Estado cliente = (Estado) manager.getEstados().search(clientenombre);
        MostrarCliente.setText(cliente.toPrint());
        }catch(Exception e){
        MostrarCliente.setText("El cliente "+clientenombre+" no ha sido encontrado.\n"
                + "Porfavor ingrese otro Nombre y Apellido. ");
        }
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void BuscarCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCheckOutActionPerformed
        // TODO add your handling code here:
        String clientenombre = CheckOutText.getText();
        try{
            Estado cliente = (Estado) manager.getEstados().delete(clientenombre);
            if (cliente.equals(null)){
                MostrarCheckOut.setText("El cliente '"+clientenombre+"' no ha sido encontrado.\n"
                + "Porfavor ingrese otro Nombre y Apellido. ");
            }else{
                MostrarCheckOut.setText("Se le hizo check out al cliente "+cliente.getName()+" "+cliente.getApellido()+"\nde forma exitosa\n\n"+cliente.toPrint());
                Historico persona = new Historico(0,cliente.getName(),cliente.getApellido(),cliente.getEmail(),cliente.getGenero(),cliente.getLlegada(), (int) cliente.getData());
                Habitacion hab = (Habitacion) manager.getHab_historico().search(persona.getNum_hab(), manager.getHab_historico().getRoot());
                hab.getHuespedes().insertLastN(persona);
                editado=true;
            }
        }catch(Exception e){
            MostrarCheckOut.setText("El cliente "+clientenombre+" no ha sido encontrado.\n"
                + "Porfavor ingrese otro Nombre y Apellido. ");
        }
    }//GEN-LAST:event_BuscarCheckOutActionPerformed

    private void BuscarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCheckInActionPerformed
        // TODO add your handling code here:
        String inputCI = CheckInText.getText();
        try{
            int ci = Integer.parseInt(inputCI.replace(".","").replace(" ",""));
            Reserva test = (Reserva) manager.getReservas().search(ci,manager.getReservas().getRoot());
            if (test!=null) {
                CheckInMostrar.setText("El cliente "+test.getNombre()+" "+test.getApellido()+" hizo check in!\n\n"+test.toPrint());
                manager.getHab_historico().search(ci, manager.getHab_historico().getRoot());

                int numHab = 1;
                boolean found = false;
                String hab1 = test.getTipo_hab();
                while (!found){
                    Habitacion hab = (Habitacion) manager.getHab_historico().search(numHab, manager.getHab_historico().getRoot());
                    String seq = ","+numHab+",";
                    //System.out.println(manager.getEstados().ocupados());
                    if (!manager.getEstados().ocupados().contains(seq)) {
                        String hab2 = hab.getTipo_hab();
                        
                        if (hab1.equals(hab2)) {
                        Estado cliente = new Estado(numHab,test.getNombre(),test.getApellido(),test.getEmail(),test.getGenero(),test.getCelular(),test.getLlegada());
                        manager.getReservas().DeleteReserva(ci, (Reserva) manager.getReservas().getRoot());
                        String nombre = cliente.getName().toLowerCase().replace(" ", "");
                        String apellido = cliente.getApellido().toLowerCase().replace(" ", "");
                        String name = nombre+apellido;
                        manager.getEstados().insert(name, cliente);
                        found = true;
                        editado=true;
                        }
                    }
                    numHab+=1;
                }
                
                


            }else{
                    
                CheckInMostrar.setText("No se ha encontrado una reserva afiliada \ncon un cliente de cedula: "+ci);
            }
            
        }catch(Exception e){
            CheckInMostrar.setText("No se ha encontrado una reserva afiliada \ncon un cliente de cedula: "+inputCI);
        }
    }//GEN-LAST:event_BuscarCheckInActionPerformed

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        // TODO add your handling code here:
        ExitBtn.setBackground(Color.red);
        XExit.setForeground(Color.white);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        // TODO add your handling code here:
        ExitBtn.setBackground(new Color(241,243,249));
        XExit.setForeground(new Color(60,63,65));
    }//GEN-LAST:event_ExitBtnMouseExited

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        // TODO add your handling code here:
        if (!editado) {
            System.exit(0);
        }else{
            String[] options = { "Si", "No"};
            ImageIcon icon = new ImageIcon("/GUI/Icon/save.png");
            var selection = JOptionPane.showOptionDialog(null, "Desea guardar sus cambios?", "Guardar", 0, 3, icon, options, options[0]);
            if (selection == 0) {
                manager.saveChanges();
                System.exit(0);
            }
            if (selection == 1) { 
                System.exit(0);
            }
        }
        
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void ReservaTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaTextMousePressed
        // TODO add your handling code here:
        ReservaText.setText("");
    }//GEN-LAST:event_ReservaTextMousePressed

    private void CheckInTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckInTextMousePressed
        // TODO add your handling code here:
        CheckInText.setText("");
    }//GEN-LAST:event_CheckInTextMousePressed

    private void CheckOutTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutTextMousePressed
        // TODO add your handling code here:
        CheckOutText.setText("");
    }//GEN-LAST:event_CheckOutTextMousePressed

    private void ClienteTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteTextMousePressed
        // TODO add your handling code here:
        ClienteText.setText("");
    }//GEN-LAST:event_ClienteTextMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JButton BuscarCheckIn;
    private javax.swing.JButton BuscarCheckOut;
    private javax.swing.JButton BuscarCheckOut1;
    private javax.swing.JButton BuscarCliente;
    private javax.swing.JButton BuscarReserva;
    private javax.swing.JPanel CheckIn;
    private javax.swing.JPanel CheckInBut;
    private javax.swing.JTextArea CheckInMostrar;
    private javax.swing.JTextField CheckInText;
    private javax.swing.JPanel CheckOut;
    private javax.swing.JPanel CheckOutBut;
    private javax.swing.JTextField CheckOutText;
    private javax.swing.JTextField ClienteText;
    private javax.swing.JPanel Default;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JTextField HistorialText;
    private javax.swing.JPanel History;
    private javax.swing.JPanel HistoryBut;
    private javax.swing.JPanel Huesped;
    private javax.swing.JPanel HuespedesBut;
    private javax.swing.JTextArea MostrarCheckOut;
    private javax.swing.JTextArea MostrarCliente;
    private javax.swing.JTextArea MostrarHistorial;
    private javax.swing.JTextArea MostrarReseva;
    private javax.swing.JLabel Nombres;
    private javax.swing.JPanel Paneles;
    private javax.swing.JTextField ReservaText;
    private javax.swing.JPanel Reservas;
    private javax.swing.JPanel ReservasBut;
    private javax.swing.JLabel XExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
